l_english:
 SETTINGS_PAGE_GRAPHICS: "Grafika"
 SETTINGS_PAGE_GAME: "Gra"
 SETTINGS_PAGE_SYSTEM: "System"
 SETTINGS_PAGE_CONTROLS: "Sterowanie"
 SETTINGS_PAGE_EDITOR: "Edytor"
 SETTINGS_PAGE_INTERFACE: "Interfejs"
 SETTINGS_PAGE_AUDIO: "Dźwięk"
 SETTINGS_CATEGORY_SCREEN: "Ekran"
 SETTINGS_CATEGORY_QUALITY: "Jakość"
 OPTION_EASY: "Łatwy"
 OPTION_NORMAL: "Normalny"
 OPTION_HARD: "Trudny"
 OPTION_NEVER: "Nigdy"
 OPTION_MONTHLY: "Co miesiąc"
 OPTION_HALFYEAR: "Co pół roku"
 OPTION_YEARLY: "Co rok"
 OPTION_FIVE_YEAR: "Co pięć lat"
 OPTION_NO_AUTOSAVE: "Brak autozapisu"
 SETTINGS_CATEGORY_ACCOUNT: "Konto"
 SETTINGS_CATEGORY_SYSTEM: "System"
 SETTINGS_CATEGORY_CONTROLS: "Sterowanie"
 SETTINGS_CATEGORY_CAMERA: "Kamera"
 SETTINGS_CATEGORY_AUDIO: "Dźwięk"
 SETTINGS_CATEGORY_GUI: "GUI"
 SETTINGS_CATEGORY_INPUT_BINDINGS: ""
 DISCARD: "Odrzuć"
 SAVE_AND_CLOSE: "OK"
 SETTINGS: "Ustawienia"
 REQUIRES_RESTART: "Wymaga restartu"
 REQUIRE_RESTART_DESCRIPTION: "Niektóre ustawienia zaczną działać dopiero po ponownym uruchomieniu gry."
 SETTINGS_INPUT_REMAP_INPUT: ""
 SETTINGS_INPUT_CONFIRM: "Potwierdź"
 SETTINGS_INPUT_CANCEL: "Anuluj"
 SETTINGS_INPUT_CLEAR: "Wyczyść"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Zapisz profil"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Wczytaj profil"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "Przywróć domyślne"
 SETTINGS_INPUT_BINDING_TEXT: ""
 SETTINGS_INPUT_BINDING_WARNING_TEXT: ""
