l_english:
 SETTING_AUTOSAVE: ""
 SETTING_DEBUG_SAVES: ""
 SETTING_TUTORIAL: "Samouczek"
 SETTING_DISABLED_HINTS: ""
 SETTING_FOCUS_ON_COMBAT: ""
 SETTING_REALM_BORDERS_AGAINST_WATER: ""
 SETTING_TOOLTIP_DELAY: ""
 SETTING_TOOLTIP_DELAY_TOOLTIP: ""
 SETTING_TOOLTIP_UNLOCK_TIME: ""
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: ""
 SETTING_TOOLTIP_LOCK_TIME: ""
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: ""
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: ""
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: ""
 SETTING_Sound_Effects: ""
 SETTING_Sound_Effects_TOOLTIP: ""
 SETTING_Ambience: ""
 SETTING_Ambience_TOOLTIP: ""
 SETTING_TOOLTIP_MODE: ""
 SETTING_TOOLTIP_MODE_TOOLTIP: ""
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: ""
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP: ""
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION: ""
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP: ""
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER: ""
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP: ""
 SETTINGS_CATEGORY_INTERFACE_MISC: ""
 SETTINGS_CATEGORY_TOOLTIPS: ""
 SETTINGS_CATEGORY_SFX: ""
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Generał"
 SETTINGS_CATEGORY_MAP_CONTROLS: ""
 SETTINGS_CATEGORY_SAVE_GAMES: ""
 SETTINGS_CATEGORY_LANGUAGE: "Język"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: ""
 SETTINGS_CATEGORY_GAME_PORTRAITS: ""
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS: ""
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP: ""
 NEVER: "Nigdy"
 MONTHLY: "Co miesiąc"
 HALFYEAR: "Co 6 miesięcy"
 YEARLY: "Co roku"
 FIVE_YEAR: "Co 5 lat"
 SETTINGS_CATEGORY_TUTORIAL: "Samouczek"
 SETTING_REACTIVE_TUTORIAL: ""
 SETTING_REACTIVE_TUTORIAL_TOOLTIP: ""
 SETTING_SHOW_SUGGESTIONS: ""
 SETTING_SHOW_SUGGESTIONS_TOOLTIP: ""
 RESET_REACTIVE_ADVICE: ""
 RESET_REACTIVE_ADVICE_TOOLTIP: ""
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE: ""
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT: ""
 SETTING_ADVANCED_SHADERS: ""
 SETTING_ADVANCED_SHADERS_TOOLTIP: ""
 BASED_ON_ZOOM_LEVEL: ""
 ALWAYS_HIDE: ""
 ALWAYS_SHOW: ""
 SETTING_HIDE_COAST_BORDER_ON_ZOOM: ""
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP: ""
