l_english:
 SETTING_VALUE_NONE: "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
 SETTING_VALUE_SECONDS: "$VALUE$ sekund"
 SETTING_VALUE_MINUTES: "$VALUE$ minut"
 SETTING_RENDERER: "Renderowanie"
 SETTING_VSYNC: "VSync"
 SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!Sprawia, że gra generuje taką ilość klatek na sekundę, jaką jest w stanie wyświetlić twój monitor, co zmniejsza efekt rozdarcia ekranu.\n\nWyłączenie tej opcji może zwiększyć wydajność."
 SETTING_PORTRAIT_MULTI_SAMPLING: "Wielopróbkowanie portretu"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: ""
 SETTING_MULTI_SAMPLING: "Antyaliasing (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!Zastosowanie wielopróbkowego antyaliasingu (MSAA) sprawi, że krawędzie obiektów będą bardziej gładkie.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_ANTI_ALIASING: "Antyaliasing"
 SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!Użycie anti-aliasingu sprawi, że krawędzie obrazu będą gładsze.\n\nFXAA jest rekomendowane."
 OPTION_ANTI_ALIASING_DISABLED: "Nieaktywny"
 OPTION_ANTI_ALIASING_FXAA: "FXAA"
 SETTING_ANISOTROPIC_FILTERING: "Filtrowanie tekstur"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Zastosowanie filtrowania anizotropowego sprawi, że oteksturowane powierzchnie będą wyglądać lepiej.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_FULLSCREEN_RESOLUTION: "Rozdzielczość"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP: "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Określa jakość obrazu w grze.\n\nNiższa rozdzielczość może zwiększyć wydajność.\n\n#X Rozdzielczość gry z nieobsługiwanym współczynnikiem proporcji może powodować wyświetlanie interfejsów poza ekranem#!"
 SETTING_WINDOWED_RESOLUTION: "Rozdzielczość w oknie"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP: "Rozdzielczość gry. Wyższa rozdzielczość jest bardziej wymagająca.\n\n#X Rozdzielczość gry z nieobsługiwanym współczynnikiem proporcji może powodować wyświetlanie interfejsów poza ekranem#!"
 SETTING_RENDER_SCALE: "Skala renderowania"
 SETTING_RENDER_SCALE_TOOLTIP: ""
 SETTING_RENDER_SCALE_FORMAT: "$VALUE|%0$"
 SETTING_DISPLAY: "Monitor"
 SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!Jeśli do twojego komputera jest podłączonych wiele monitorów, wybierz ten, który będzie używany przez grę."
 SETTING_GRAPHICS_DEVICE: "Karta graficzna"
 SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!Określa, która karta graficzna będzie używana przez grę. \n\nUżycie zintegrowanej karty graficznej lub renderowania programowego może zmniejszyć wydajność."
 SETTING_SHADOW_MAP_RESOLUTION: "Jakość cieni"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Określa rozdzielczość, z użyciem której renderowane są mapy cieni, jeśli cienie są włączone.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_DISPLAY_MODE: "Tryb wyświetlania"
 SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$\n#!Określa sposób wyświetlania gry na twoim ekranie"
 SETTING_BLOOM: "Bloom"
 SETTING_MESH_LOD_BIAS: "Jakość poziomu szczegółów siatki"
 SETTING_MESH_LOD_FADE: "Zanikanie poziomu szczegółów siatki"
 SETTING_TERRAIN_SMOOTHING: "Wygładzanie terenu"
 OPTION_FULLSCREEN: "Pełny ekran"
 OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$\n#!Wyświetlanie gry na całym ekranie. Ustawienie rozdzielczości zmieni ostrość obrazu."
 OPTION_WINDOWED: "W oknie"
 OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$\n#!Wyświetlanie gry w oknie. Ustawienie rozdzielczości zmienia rozmiar okna."
 OPTION_DISABLED: "Nieaktywne"
 OPTION_OFF: "Wyłączone"
 OPTION_LOW: "Niskie"
 OPTION_MEDIUM: "Średnie"
 OPTION_HIGH: "Wysokie"
 OPTION_ULTRA: "Ultra"
 OPTION_CUSTOM: "Własne"
 OPTION_DEFAULT: "Domyślne"
 SETTINGS_CATEGORY_UI: "Interfejs"
 SETTINGS_CATEGORY_GAME: "Gra"
 SETTING_TEXTURE_QUALITY: "Jakość tekstur"
 SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$#!\nUstala rozdzielczość załadowanych tekstur.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_QUALITY: "Predefiniowane ustawienia jakości"
 SETTING_SFX: "SFX"
 SETTING_UI: "Interfejs"
 SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$\n#!Wybierz jeden z poniższych wariantów ustawień zaawansowanych opcji graficznych.\n\nNiskie ustawienie predefiniowane zwiększy wydajność."
 SETTING_BLOOM_TOOLTIP: "#T $SETTING_BLOOM$\n#!Pozwala na uzyskanie efektu \"bloom\", w którym bardzo jasne światła rozchodzą się na inne części obrazu.\n\nWyłączenie go może zwiększyć wydajność."
 SETTING_DOF_TOOLTIP: ""
 SETTING_MAP_SSAO_TOOLTIP: ""
 SETTING_REFRACTION_TOOLTIP: "Ustala, czy refrakcje pojawiają się na wodzie."
 SETTING_REFRACTION_QUALITY_TOOLTIP: "#T $SETTING_REFRACTION_QUALITY$#!\nKontroluje jakość załamań wody, jeśli są one włączone.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP: "#T $SETTING_MAPOBJECT_QUALITY$#!\nOkreśla najwyższy poziom jakości obiektów na mapy (takich jak budowle).\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_MESH_LOD_BIAS_TOOLTIP: "#T $SETTING_MESH_LOD_BIAS$#!\nOkreśla jakość LOD (poziom detali) na mapie, takie jak modele jednostek.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_MESH_LOD_FADE_TOOLTIP: "#T $SETTING_MESH_LOD_FADE$\n#!Po włączeniu, modele 3D płynnie przechodzą pomiędzy różnymi poziomami szczegółowości (LOD) podczas powiększania i pomniejszania.\n\nWyłączenie podniesie wydajność."
 SETTING_PROVINCE_NAMES_TOOLTIP: "Określa, jak nazwy miast i prowincji pojawiają się na mapie."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "Określa, czy teren nie do przebycia znajduje się w granicach danego kraju na mapie."
 SETTING_LANGUAGE_TOOLTIP: "#T $SETTING_LANGUAGE$#!\nOkreśla język interfejsu użytkownika."
 SETTING_ACCOUNT_EMAIL_TOOLTIP: "Twój email do konta Paradox"
 SETTING_FRAMERATE_CAP: "Maksymalne FPS"
 SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\nOgraniczenie liczby klatek renderowanych przez grę.\n\nNiższe ustawienia mogą zmniejszyć zużycie energii."
 OPTION_CAP_30: "30"
 OPTION_CAP_60: "60"
 OPTION_CAP_90: "90"
 OPTION_CAP_120: "120"
 OPTION_CAP_144: "144"
 OPTION_CAP_165: "165"
 SETTING_ANIMATION_SPEED: "Prędkość animacji"
 SETTING_GUI_SCALING: "Skalowanie GUI"
 SETTING_GUI_SCALING_TOOLTIP: "#T $SETTING_GUI_SCALING$\n#!Ustawia skalę całego interfejsu użytkownika. Przydatne w przypadku wyższych rozdzielczości ekranu.\n\n#X Ustawienie go zbyt wysoko spowoduje, że interfejs nie będzie prawidłowo dopasowany do ekranu!#!"
 SETTING_SCREEN_EDGE_SCROLL_MODE: ""
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: ""
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: ""
 SETTING_SCREEN_EDGE_SCROLL_DISABLED: ""
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: ""
 SETTING_SCROLL_SPEED: "Prędkość przewijania kamery"
 SETTING_SCROLL_SPEED_TOOLTIP: "#T $SETTING_SCROLL_SPEED$#!\nOkreśla szybkość przesuwania mapy podczas korzystania z klawiatury lub myszy."
 SETTING_CAMERA_ROTATION_SPEED: "Prędkość obrotu kamery"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: ""
 SETTING_ZOOM_SPEED: ""
 SETTING_ZOOM_SPEED_TOOLTIP: ""
 SETTING_MOUSE_CURSOR_ZOOM_MODE: ""
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: ""
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: ""
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: ""
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: ""
 SETTING_INPUT_DEVICE: "Urządzenia wejściowe"
 SETTING_EDITOR: "Edytor"
 SETTING_EDITOR_POSTFIX: "Edytor postfix"
 SETTING_EDITOR_OPEN_FILE_FORMAT: "Komenda otwierania pliku w edytorze"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: "Logi komend"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: ""
 SETTING_GRACEFUL_EXIT: "Miłosierne wyjście"
 SETTING_LANGUAGE: "Język"
 MOUSE_AND_KEYBOARD: "Mysz i klawiatura"
 GAMEPAD: "Kontroler"
 SETTING_MULTISAMPLING_DISABLED: "Nieaktywne"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED: ""
 SETTING_ANISOTROPIC_FILTERING_DISABLED: "Nieaktywne"
 SETTING_CAMERA_TILT: "Przechylenie kamery"
 SETTING_CAMERA_STRATEGY: "Typ kamery"
 SETTING_CENTERED_ZOOM_IN: "Wyśrodkowane powiększenie"
 SETTING_CAMERA_SPEED: "Prędkość kamery"
 CAMERA_TABLETOP: "Kamera od góry"
 CAMERA_FPS: "Kamera FPS"
 CAMERA_WASD: "Kamera w stylu WASD"
 SETTING_Music: "Muzyka"
 SETTING_Ambient: "Otoczenie"
 SETTING_Effects: "Efekty"
 SETTING_Master: "Głośność gry"
 SETTING_Master_TOOLTIP: "#T Głośność gry\n#!Ustawia głośność całej gry."
 SETTING_Music_TOOLTIP: "#T Głośność muzyki\n#!Ustawia głośność muzyki."
 SETTING_Ambient_TOOLTIP: "#T Głośność otoczenia\n#!Ustawia głośność otoczenia."
 SETTING_SFX_TOOLTIP: "#T Głośność efektów SFX\n#!Ustawia głośność efektów dźwiękowych, takich jak walka."
 SETTING_UI_TOOLTIP: "#T Głośność interfejsu\n#!Ustawia głośność interfejsu."
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "Poziom dziennika debugowania"
 SETTING_AUTOSAVE: "Częstotliwość autozapisu"
 SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_AUTOSAVE$\n#!Określa, jak często gra będzie zapisywana automatycznie."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "Określa, czy autozapisy mają być przechowywane w chmurze."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP: "Określa, czy kamera ma być zawsze skierowana na północ."
 NO_AUTOSAVE: "Brak autozapisu"
 SETTINGS_FILE_TRANSFER_SPEED: "Prędkość transferu danych"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T Prędkość transferu danych#!\nOkreśla maksymalną prędkość transferu danych zapisu gry w lobby dla wielu graczy.\n\nNiższe ustawienia mogą poprawić stabilność sieci podczas dołączania do gry wieloosobowej, ale mają negatywny wpływ na czas ładowania tych gier."
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: ""
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: ""
 SETTINGS_CATEGORY_ACCESSIBILITY: ""
 SETTING_COLOR_BLIND_MODE: ""
 SETTING_COLOR_BLIND_MODE_TOOLTIP: ""
