l_english:
 SETTING_VALUE_NONE: "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
 SETTING_VALUE_SECONDS: "$VALUE$ sekund"
 SETTING_RENDERER: ""
 SETTING_VSYNC: "VSync"
 SETTING_VSYNC_TOOLTIP: ""
 SETTING_MULTI_SAMPLING: "Antyaliasing (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP: ""
 SETTING_ANTI_ALIASING: "Antyaliasing"
 SETTING_ANTI_ALIASING_TOOLTIP: ""
 OPTION_ANTI_ALIASING_DISABLED: "Wyłączone"
 OPTION_ANTI_ALIASING_FXAA: "FXAA"
 SETTING_ANISOTROPIC_FILTERING: "Filtrowanie tekstur"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: ""
 SETTING_FULLSCREEN_RESOLUTION: "Rozdzielczość"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP: ""
 SETTING_WINDOWED_RESOLUTION: "Rozdzielczość w oknie"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP: ""
 SETTING_DISPLAY: "Monitor"
 SETTING_DISPLAY_TOOLTIP: ""
 SETTING_GRAPHICS_DEVICE: "Karta graficzna"
 SETTING_GRAPHICS_DEVICE_TOOLTIP: ""
 SETTING_SHADOW_MAP_RESOLUTION: "Jakość cieni"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: ""
 SETTING_DISPLAY_MODE: "Tryb wyświetlania"
 SETTING_DISPLAY_MODE_TOOLTIP: ""
 SETTING_BLOOM: "Bloom"
 SETTING_MESH_LOD_BIAS: ""
 SETTING_MESH_LOD_FADE: ""
 SETTING_TERRAIN_SMOOTHING: "Wygładzanie terenu"
 OPTION_FULLSCREEN: "Pełny ekran"
 OPTION_FULLSCREEN_TOOLTIP: ""
 OPTION_BORDERLESS_FULLSCREEN: ""
 OPTION_BORDERLESS_FULLSCREEN_TOOLTIP: ""
 OPTION_WINDOWED: "W oknie"
 OPTION_WINDOWED_TOOLTIP: ""
 OPTION_DISABLED: "Wyłączone"
 OPTION_OFF: "Wyłączone"
 OPTION_LOW: "Niska"
 OPTION_MEDIUM: "Średnia"
 OPTION_HIGH: "Wysoka"
 OPTION_ULTRA: "Ultra"
 OPTION_CUSTOM: "Własne"
 OPTION_DEFAULT: "Domyślne"
 SETTINGS_CATEGORY_UI: "Interfejs"
 SETTINGS_CATEGORY_GAME: "Gra"
 SETTING_TEXTURE_QUALITY: "Jakość tekstur"
 SETTING_TEXTURE_QUALITY_TOOLTIP: ""
 SETTING_QUALITY: "Predefiniowane ustawienia jakości"
 SETTING_SFX: "SFX"
 SETTING_UI: "Interfejs"
 SETTING_QUALITY_TOOLTIP: ""
 SETTING_BLOOM_TOOLTIP: ""
 SETTING_REFRACTION_TOOLTIP: ""
 SETTING_REFRACTION_QUALITY_TOOLTIP: ""
 SETTING_MAPOBJECT_QUALITY_TOOLTIP: ""
 SETTING_MESH_LOD_BIAS_TOOLTIP: ""
 SETTING_MESH_LOD_FADE_TOOLTIP: ""
 SETTING_PROVINCE_NAMES_TOOLTIP: ""
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: ""
 SETTING_LANGUAGE_TOOLTIP: ""
 SETTING_ACCOUNT_EMAIL_TOOLTIP: ""
 SETTING_FRAMERATE_CAP: ""
 SETTING_FRAMERATE_CAP_TOOLTIP: ""
 OPTION_CAP_30: "30"
 OPTION_CAP_60: "60"
 OPTION_CAP_90: "90"
 OPTION_CAP_120: "120"
 OPTION_CAP_144: "144"
 OPTION_CAP_165: "165"
 SETTING_ANIMATION_SPEED: "Prędkość animacji"
 SETTING_GUI_SCALING: "Skalowanie GUI"
 SETTING_GUI_SCALING_TOOLTIP: ""
 SETTING_MOUSE_PANNING: ""
 SETTING_MOUSE_PANNING_TOOLTIP: ""
 SETTING_SCROLL_SPEED: ""
 SETTING_CAMERA_ROTATION_SPEED: ""
 SETTING_ZOOM_SPEED: ""
 SETTING_INPUT_DEVICE: ""
 SETTING_EDITOR: "Edytor"
 SETTING_EDITOR_POSTFIX: ""
 SETTING_EDITOR_OPEN_FILE_FORMAT: ""
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: ""
 SETTING_GRACEFUL_EXIT: ""
 SETTING_LANGUAGE: "Język"
 MOUSE_AND_KEYBOARD: ""
 GAMEPAD: "Kontroler"
 SETTING_MULTISAMPLING_DISABLED: "Wyłączone"
 SETTING_ANISOTROPIC_FILTERING_DISABLED: "Wyłączone"
 SETTING_CAMERA_TILT: ""
 SETTING_CAMERA_STRATEGY: ""
 SETTING_CENTERED_ZOOM_IN: ""
 SETTING_CAMERA_SPEED: ""
 CAMERA_TABLETOP: ""
 CAMERA_FPS: ""
 CAMERA_WASD: ""
 SETTING_Music: "Muzyka"
 SETTING_Ambient: "Otoczenie"
 SETTING_Effects: "Efekty"
 SETTING_Master: "Ogólna"
 SETTING_Master_TOOLTIP: ""
 SETTING_Music_TOOLTIP: ""
 SETTING_Ambient_TOOLTIP: ""
 SETTING_SFX_TOOLTIP: ""
 SETTING_UI_TOOLTIP: ""
 SETTING_AUTOSAVE_TOOLTIP: ""
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: ""
 SETTING_CAMERA_FACE_NORTH_TOOLTIP: ""
 NO_AUTOSAVE: "Brak autozapisu"
