l_english:
 SETTING_VALUE_WARNING: "$VALUE|0X$"
 SETTING_VALUE_PERCENTAGE_WARNING: "$VALUE|%0X$"
 RECOMMENDED_GUI_SCALE_TOO_HIGH: "#X Skalowanie powyżej $VALUE|%0$ spowoduje wyświetlenie elementów interfejsu poza ekranem#!"
 RECOMMENDED_GUI_SCALE: "Skalowania powyżej $VALUE|%0$ spowoduje wyświetlenie elementów interfejsu poza ekranem"
