l_english:
 SETTING_VALUE_PERCENTAGE_WARNING:0 "$VALUE|%0X$"
 RECOMMENDED_GUI_SCALE_TOO_HIGH:0 "#X Scaling above $VALUE|%0$ will cause interfaces to appear outside the screen#!"
 RECOMMENDED_GUI_SCALE:0 "Scaling above $VALUE|%0$ will cause interfaces to appear outside the screen"
