l_english:
 SETTING_VALUE_NONE:0 "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE:0 "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE:0 "$VALUE|%0$"
 SETTING_VALUE_SECONDS:0 "$VALUE$ sekund"
 SETTING_VALUE_MINUTES:0 "$VALUE$ minut"
 SETTING_RENDERER:0 "Renderowanie"
 SETTING_VSYNC:0 "VSync"
 SETTING_VSYNC_TOOLTIP:0 "#T $SETTING_VSYNC$\n#!Sprawia, że gra generuje taką ilość klatek na sekundę, jaką jest w stanie wyświetlić twój monitor, co zmniejsza efekt rozdarcia ekranu.\n\nWyłączenie tej opcji może zwiększyć wydajność."
 SETTING_PORTRAIT_MULTI_SAMPLING:0 "Wielopróbkowanie portretu"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP:0 "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Using multi-sample for Alpha-To-Coverage to make hair blending smoother.\n\nLower settings increase performance."
 SETTING_MULTI_SAMPLING:0 "Antyaliasing (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP:0 "#T $SETTING_MULTI_SAMPLING$\n#!Zastosowanie wielopróbkowego antyaliasingu (MSAA) sprawi, że krawędzie obiektów będą bardziej gładkie.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_ANTI_ALIASING:0 "Antyaliasing"
 SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!Użycie anti-aliasingu sprawi, że krawędzie obrazu będą gładsze.\n\nFXAA jest rekomendowane."
 OPTION_ANTI_ALIASING_DISABLED:0 "Nieaktywny"
 OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
 SETTING_ANISOTROPIC_FILTERING:0 "Filtrowanie tekstur"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP:0 "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Zastosowanie filtrowania anizotropowego sprawi, że oteksturowane powierzchnie będą wyglądać lepiej.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_FULLSCREEN_RESOLUTION:0 "Rozdzielczość"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:0 "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Określa jakość obrazu w grze.\n\nNiższa rozdzielczość może zwiększyć wydajność.\n\n#X Rozdzielczość gry z nieobsługiwanym współczynnikiem proporcji może powodować wyświetlanie interfejsów poza ekranem#!"
 SETTING_WINDOWED_RESOLUTION:0 "Rozdzielczość w oknie"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP:0 "Rozdzielczość gry. Wyższa rozdzielczość jest bardziej wymagająca.\n\n#X Rozdzielczość gry z nieobsługiwanym współczynnikiem proporcji może powodować wyświetlanie interfejsów poza ekranem#!"
 SETTING_RENDER_SCALE:0 "Render Scale"
 SETTING_RENDER_SCALE_TOOLTIP:0 "#T $SETTING_RENDER_SCALE$#!\nThe scale of the render resolution of the game relative to the main resolution, excluding the user interface.\n\nLower settings may increase performance but will reduce overall fidelity, while going above 100% may increase fidelity but will likely degrade performance."
 SETTING_RENDER_SCALE_FORMAT:0 "$VALUE|%0$"
 SETTING_DISPLAY:0 "Monitor"
 SETTING_DISPLAY_TOOLTIP:0 "#T $SETTING_DISPLAY$\n#!Jeśli do twojego komputera jest podłączonych wiele monitorów, wybierz ten, który będzie używany przez grę."
 SETTING_GRAPHICS_DEVICE:0 "Karta graficzna"
 SETTING_GRAPHICS_DEVICE_TOOLTIP:0 "#T $SETTING_GRAPHICS_DEVICE$\n#!Określa, która karta graficzna będzie używana przez grę. \n\nUżycie zintegrowanej karty graficznej lub renderowania programowego może zmniejszyć wydajność."
 SETTING_SHADOW_MAP_RESOLUTION:0 "Jakość cieni"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:0 "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Określa rozdzielczość, z użyciem której renderowane są mapy cieni, jeśli cienie są włączone.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_DISPLAY_MODE:0 "Tryb wyświetlania"
 SETTING_DISPLAY_MODE_TOOLTIP:0 "#T $SETTING_DISPLAY_MODE$\n#!Określa sposób wyświetlania gry na twoim ekranie"
 SETTING_BLOOM:0 "Bloom"
 SETTING_MESH_LOD_BIAS:0 "Jakość poziomu szczegółów siatki"
 SETTING_MESH_LOD_FADE:0 "Zanikanie poziomu szczegółów siatki"
 SETTING_TERRAIN_SMOOTHING:0 "Wygładzanie terenu"
 OPTION_FULLSCREEN:0 "Pełny ekran"
 OPTION_FULLSCREEN_TOOLTIP:0 "#T $OPTION_FULLSCREEN$\n#!Wyświetlanie gry na całym ekranie. Ustawienie rozdzielczości zmieni ostrość obrazu."
 OPTION_WINDOWED:0 "W oknie"
 OPTION_WINDOWED_TOOLTIP:0 "#T $OPTION_WINDOWED$\n#!Wyświetlanie gry w oknie. Ustawienie rozdzielczości zmienia rozmiar okna."
 OPTION_DISABLED:0 "Nieaktywne"
 OPTION_OFF:0 "Wyłączone"
 OPTION_LOW:0 "Niskie"
 OPTION_MEDIUM:0 "Średnie"
 OPTION_HIGH:0 "Wysokie"
 OPTION_ULTRA:0 "Ultra"
 OPTION_CUSTOM:0 "Własne"
 OPTION_DEFAULT:0 "Domyślne"
 SETTINGS_CATEGORY_UI:0 "Interfejs"
 SETTINGS_CATEGORY_GAME:0 "Gra"
 SETTING_TEXTURE_QUALITY:0 "Jakość tekstur"
 SETTING_TEXTURE_QUALITY_TOOLTIP:0 "#T $SETTING_TEXTURE_QUALITY$#!\nUstala rozdzielczość załadowanych tekstur.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_QUALITY:0 "Predefiniowane ustawienia jakości"
 SETTING_SFX:0 "SFX"
 SETTING_UI:0 "Interfejs"
 SETTING_QUALITY_TOOLTIP:0 "#T $SETTING_QUALITY$\n#!Wybierz jeden z poniższych wariantów ustawień zaawansowanych opcji graficznych.\n\nNiskie ustawienie predefiniowane zwiększy wydajność."
 SETTING_BLOOM_TOOLTIP:0 "#T $SETTING_BLOOM$\n#!Pozwala na uzyskanie efektu "bloom", w którym bardzo jasne światła rozchodzą się na inne części obrazu.\n\nWyłączenie go może zwiększyć wydajność."
 SETTING_DOF_TOOLTIP:0 "#T $SETTING_DOF$\n#!Enables depth of field to simulate a camera lens, blurs out-of-focus points of the image.\n\nTurning it off may increase performance."
 SETTING_MAP_SSAO_TOOLTIP:0 "#T $SETTING_MAP_SSAO$\n#!Determines whether screen space ambient occlusion should be applied to the map.\n\nTurning it off may increase performance."
 SETTING_REFRACTION_TOOLTIP:0 "Ustala, czy refrakcje pojawiają się na wodzie."
 SETTING_REFRACTION_QUALITY_TOOLTIP:0 "#T $SETTING_REFRACTION_QUALITY$#!\nKontroluje jakość załamań wody, jeśli są one włączone.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP:0 "#T $SETTING_MAPOBJECT_QUALITY$#!\nOkreśla najwyższy poziom jakości obiektów na mapy (takich jak budowle).\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_MESH_LOD_BIAS_TOOLTIP:0 "#T $SETTING_MESH_LOD_BIAS$#!\nOkreśla jakość LOD (poziom detali) na mapie, takie jak modele jednostek.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_MESH_LOD_FADE_TOOLTIP:0 "#T $SETTING_MESH_LOD_FADE$\n#!Po włączeniu, modele 3D płynnie przechodzą pomiędzy różnymi poziomami szczegółowości (LOD) podczas powiększania i pomniejszania.\n\nWyłączenie podniesie wydajność."
 SETTING_PROVINCE_NAMES_TOOLTIP:0 "Określa, jak nazwy miast i prowincji pojawiają się na mapie."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "Określa, czy teren nie do przebycia znajduje się w granicach danego kraju na mapie."
 SETTING_LANGUAGE_TOOLTIP:0 "#T $SETTING_LANGUAGE$#!\nOkreśla język interfejsu użytkownika."
 SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "Twój email do konta Paradox"
 SETTING_FRAMERATE_CAP:0 "Maksymalne FPS"
 SETTING_FRAMERATE_CAP_TOOLTIP:0 "#T $SETTING_FRAMERATE_CAP$#!\nOgraniczenie liczby klatek renderowanych przez grę.\n\nNiższe ustawienia mogą zmniejszyć zużycie energii."
 OPTION_CAP_30:0 "30"
 OPTION_CAP_60:0 "60"
 OPTION_CAP_90:0 "90"
 OPTION_CAP_120:0 "120"
 OPTION_CAP_144:0 "144"
 OPTION_CAP_165:0 "165"
 SETTING_ANIMATION_SPEED:0 "Prędkość animacji"
 SETTING_GUI_SCALING:0 "Skalowanie GUI"
 SETTING_GUI_SCALING_TOOLTIP:0 "#T $SETTING_GUI_SCALING$\n#!Ustawia skalę całego interfejsu użytkownika. Przydatne w przypadku wyższych rozdzielczości ekranu.\n\n#X Ustawienie go zbyt wysoko spowoduje, że interfejs nie będzie prawidłowo dopasowany do ekranu!#!"
 SETTING_SCREEN_EDGE_SCROLL_MODE:0 "Mouse Pan"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE:0 "Free"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS:0 "8 directions"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED:0 "Disabled"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP:0 "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nHow the camera behaves when panning with the mouse."
 SETTING_SCROLL_SPEED:0 "Prędkość przewijania kamery"
 SETTING_SCROLL_SPEED_TOOLTIP:0 "#T $SETTING_SCROLL_SPEED$#!\nOkreśla szybkość przesuwania mapy podczas korzystania z klawiatury lub myszy."
 SETTING_CAMERA_ROTATION_SPEED:0 "Prędkość obrotu kamery"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP:0 "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nThe camera rotation speed."
 SETTING_ZOOM_SPEED:0 "Zoom Speed"
 SETTING_ZOOM_SPEED_TOOLTIP:0 "#T $SETTING_ZOOM_SPEED$#!\nThe camera zoom speed."
 SETTING_MOUSE_CURSOR_ZOOM_MODE:0 "Zoom Behavior"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR:0 "Relative cursor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR:0 "Zoom in to cursor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR:0 "Ignore cursor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP:0 "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nHow the camera behaves relative to the mouse cursor when zooming in/out."
 SETTING_INPUT_DEVICE:0 "Urządzenia wejściowe"
 SETTING_EDITOR:0 "Edytor"
 SETTING_EDITOR_POSTFIX:0 "Edytor postfix"
 SETTING_EDITOR_OPEN_FILE_FORMAT:0 "Komenda otwierania pliku w edytorze"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "Logi komend"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT:0 "Code editor open command"
 SETTING_GRACEFUL_EXIT:0 "Miłosierne wyjście"
 SETTING_LANGUAGE:0 "Język"
 MOUSE_AND_KEYBOARD:0 "Mysz i klawiatura"
 GAMEPAD:0 "Kontroler"
 SETTING_MULTISAMPLING_DISABLED:0 "Nieaktywne"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED:0 "Disabled"
 SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "Nieaktywne"
 SETTING_CAMERA_TILT:0 "Przechylenie kamery"
 SETTING_CAMERA_STRATEGY:0 "Typ kamery"
 SETTING_CENTERED_ZOOM_IN:0 "Wyśrodkowane powiększenie"
 SETTING_CAMERA_SPEED:0 "Prędkość kamery"
 CAMERA_TABLETOP:0 "Kamera od góry"
 CAMERA_FPS:0 "Kamera FPS"
 CAMERA_WASD:0 "Kamera w stylu WASD"
 SETTING_Music:0 "Muzyka"
 SETTING_Ambient:0 "Otoczenie"
 SETTING_Effects:0 "Efekty"
 SETTING_Master:0 "Głośność gry"
 SETTING_Master_TOOLTIP:0 "#T Głośność gry\n#!Ustawia głośność całej gry."
 SETTING_Music_TOOLTIP:0 "#T Głośność muzyki\n#!Ustawia głośność muzyki."
 SETTING_Ambient_TOOLTIP:0 "#T Głośność otoczenia\n#!Ustawia głośność otoczenia."
 SETTING_SFX_TOOLTIP:0 "#T Głośność efektów SFX\n#!Ustawia głośność efektów dźwiękowych, takich jak walka."
 SETTING_UI_TOOLTIP:0 "#T Głośność interfejsu\n#!Ustawia głośność interfejsu."
 SETTING_AUDIO_DEBUG_LOG_LEVEL:0 "Poziom dziennika debugowania"
 SETTING_AUTOSAVE:0 "Częstotliwość autozapisu"
 SETTING_AUTOSAVE_TOOLTIP:0 "#T $SETTING_AUTOSAVE$\n#!Określa, jak często gra będzie zapisywana automatycznie."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "Określa, czy autozapisy mają być przechowywane w chmurze."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "Określa, czy kamera ma być zawsze skierowana na północ."
 NO_AUTOSAVE:0 "Brak autozapisu"
 SETTINGS_FILE_TRANSFER_SPEED:0 "File Transfer Speed"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP:0 "#T $File Transfer Speed$\n#!Sets the maximum speed for save game file transfers in the multiplayer lobby.\n\nLower settings might improve network stability of joining multiplayer games but have a negative effect on multiplayer load times."
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES:0 "Map Editor Auto-save (minutes)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP:0 "Map Editor Auto-save interval (minutes)"
 SETTINGS_CATEGORY_ACCESSIBILITY:0 "Accessibility"
 SETTING_COLOR_BLIND_MODE:0 "Color Blind Mode"
 SETTING_COLOR_BLIND_MODE_TOOLTIP:0 "#T $SETTING_COLOR_BLIND_MODE$\n#!Changes the colors used in text throughout the game to a set of colors that is easier to distinguish for different types of color blindness."
