l_english:
 SETTING_AUTOSAVE: "Częstotliwość autozapisu"
 SETTING_DEBUG_SAVES: "Liczba debugowanych zapisów"
 SETTING_TUTORIAL: "Samouczek"
 SETTING_DISABLED_HINTS: "Wyłączone wskazówki"
 SETTING_FOCUS_ON_COMBAT: "Zbliżenie na walkę"
 SETTING_TOOLTIP_DELAY: "Opóźnienie wskazówki"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nOkreśla opóźnienie przed pojawieniem się podpowiedzi."
 SETTING_TOOLTIP_UNLOCK_TIME: "Czas odblokowania"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nOkreśla czas po jakim wskazówka będzie odblokowana."
 SETTING_TOOLTIP_LOCK_TIME: "Czas zablokowania"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nOkreśla czas po jakim wskazówka zostanie zablokowana."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Czas zablokowania otwartej"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nOkreśla czas po jakim wskazówka zostanie zablokowana jeśli inna wskazówka jest już otwarta."
 SETTING_Sound_Effects: "Wszystkie efekty dźwiękowe"
 SETTING_Sound_Effects_TOOLTIP: "#T Głośność efektów dźwiękowych\n#!Określa głośność WSZYSTKICH efektów dźwiękowych."
 SETTING_Ambience: "Otoczenie"
 SETTING_Ambience_TOOLTIP: "#T Głośność otoczenia\n#!Określa poziom głośności efektów otoczenia."
 SETTING_TOOLTIP_MODE: "Tryb wskazówek"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nUstawia sposób, w jaki podpowiedzi \"blokują się\", włączając podpowiedzi w podpowiedziach."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Obecność myszy"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nWskazówka automatycznie blokuje się na miejscu dopóki kursor się nie odsunie."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION: "Blokada akcją"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nNaciśnij #V środkowy przycisk myszy#! aby zablokować i odblokować wskazówki."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER: "Blokada czasowa"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nJeśli kursor przez chwilę jest nieruchomy to wskazówki są blokowane. #weak (Ustawienie domyślne)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC: "Różne"
 SETTINGS_CATEGORY_TOOLTIPS: "Podpowiedzi"
 SETTINGS_CATEGORY_SFX: "Efekty dźwiękowe"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Ogólne"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Kontrola mapy"
 SETTINGS_CATEGORY_SAVE_GAMES: "Zapisane gry"
 SETTINGS_CATEGORY_LANGUAGE: "Język"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Zaawansowane"
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Portrety"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS: "Pokaż choroby i urazy na portretach"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP: "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nOkreśla, czy urazy i choroby będą widoczne na portretach postaci."
 SETTING_SHOW_NUDITY: ""
 SETTING_SHOW_NUDITY_TOOLTIP: ""
 NEVER: "Nigdy"
 MONTHLY: "Co miesiąc"
 HALFYEAR: "Co 6 miesięcy"
 YEARLY: "Co roku"
 FIVE_YEAR: "Co 5 lat"
 SETTINGS_CATEGORY_TUTORIAL: "Samouczek"
 SETTING_REACTIVE_TUTORIAL: "Pokaż reaktywną poradę"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP: "#T $SETTING_REACTIVE_TUTORIAL$#!\nUstawia, czy gra będzie wyświetlała porady w stylu samouczka w reakcji na twoje działania. Przydatne dla graczy, którzy nie mają doświadczenia z Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS: "Pokazuj sugestie"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP: "#T $SETTING_SHOW_SUGGESTIONS$#!\nUstawia, czy gra ma wyświetlać sugestie w określonych odstępach czasu. Przydatne dla graczy, którzy nie mają doświadczenia z Crusader Kings III."
 RESET_REACTIVE_ADVICE: "Zresetuj reaktywną poradę"
 RESET_REACTIVE_ADVICE_TOOLTIP: "#T Zresetuj reaktywną poradę#!\nWcześniej widziane porady reaktywne pojawią się ponownie."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE: "Zresetuj reaktywną poradę"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT: "Czy na pewno chcesz zresetować reaktywną poradę?"
 SETTING_ADVANCED_SHADERS: "Zaawansowane efekty shaderów"
 SETTING_ADVANCED_SHADERS_TOOLTIP: "#T Zaawansowane efekty cieni#!\nTa opcja włącza zaawansowane efekty cieniowania. Wyłączenie jej może zwiększyć wydajność kosztem pogorszenia wyglądu niektórych efektów (np. terenu i wody)"
 BASED_ON_ZOOM_LEVEL: "Dynamiczne"
 ALWAYS_HIDE: "Zawsze ukryte"
 ALWAYS_SHOW: "Zawsze widoczne"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM: "Granice przybrzeżne"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP: "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nTa opcja pozwoli kontrolować, kiedy powinny zostać pokazane granice morskie.\nJeśli ustawienie jest $BASED_ON_ZOOM_LEVEL$, zostaną one ukryte w przybliżeniu.\n\nWybranie $ALWAYS_SHOW$ lub $ALWAYS_HIDE$ może zwiększyć wydajność kosztem dynamicznego pojawiania granic przybrzeżnych."
