l_english:
 SETTING_AUTOSAVE:0 "Częstotliwość autozapisu"
 SETTING_DEBUG_SAVES:0 "Liczba debugowanych zapisów"
 SETTING_TUTORIAL:0 "Samouczek"
 SETTING_DISABLED_HINTS:0 "Wyłączone wskazówki"
 SETTING_FOCUS_ON_COMBAT:0 "Focus on combat"
 SETTING_TOOLTIP_DELAY:0 "Opóźnienie podpowiedzi"
 SETTING_TOOLTIP_DELAY_TOOLTIP:0 "#T $SETTING_TOOLTIP_DELAY$#!\nOkreśla opóźnienie przed pojawieniem się podpowiedzi."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Unlock Delay"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nSets the delay before tooltips are unlocked."
 SETTING_TOOLTIP_LOCK_TIME:0 "Lock Delay"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nSets the delay before tooltips are locked."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Locked Open Delay"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nSets the delay before tooltips are locked when another tooltip is already open."
 SETTING_Sound_Effects:0 "Wszystkie efekty dźwiękowe"
 SETTING_Sound_Effects_TOOLTIP:0 "#T Sound Effects Volume\n#!Sets the volume of ALL sound effects."
 SETTING_Ambience:0 "Otoczenie"
 SETTING_Ambience_TOOLTIP:0 "#T Ambience Volume\n#!Sets the volume of environmental ambience."
 SETTING_TOOLTIP_MODE:0 "Tryb podpowiedzi"
 SETTING_TOOLTIP_MODE_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE$#!\nUstawia sposób, w jaki podpowiedzi "blokują się", włączając podpowiedzi w podpowiedziach."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Mouse Tendency"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nTooltips automatically lock in place until the cursor moves away."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "Action Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nPress #V Middle Mouse#! to lock and unlock tooltips."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "Timer Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nTooltips are locked in place if the cursor does not move for a short while. #weak (Default setting.)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "Różne"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Tooltips"
 SETTINGS_CATEGORY_SFX:0 "Konkretne efekty dźwiękowe"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Ogólne"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Opcje mapy"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Zapisane gry"
 SETTINGS_CATEGORY_LANGUAGE:0 "Język"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Zaawansowane"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Portrety"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "Show graphic diseases and injuries"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nSets whether graphic injuries and diseases will be visible on character portraits."
 NEVER:0 "Nigdy"
 MONTHLY:0 "Co miesiąc"
 HALFYEAR:0 "Co 6 miesięcy"
 YEARLY:0 "Co roku"
 FIVE_YEAR:0 "Co 5 lat"
 SETTINGS_CATEGORY_TUTORIAL:0 "Samouczek"
 SETTING_REACTIVE_TUTORIAL:0 "Pokaż reaktywną poradę"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\nUstawia, czy gra będzie wyświetlała porady w stylu samouczka w reakcji na twoje działania. Przydatne dla graczy, którzy nie mają doświadczenia z Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS:0 "Pokazuj sugestie"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:0 "#T $SETTING_SHOW_SUGGESTIONS$#!\nUstawia, czy gra ma wyświetlać sugestie w określonych odstępach czasu. Przydatne dla graczy, którzy nie mają doświadczenia Crusader Kings III.""
 RESET_REACTIVE_ADVICE:0 "Zresetuj reaktywną poradę"
 RESET_REACTIVE_ADVICE_TOOLTIP:0 "#T Zresetuj reaktywną poradę#!\nWcześniej widziane porady reaktywne pojawią się ponownie."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "Zresetuj reaktywną poradę"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "Czy na pewno chcesz zresetować reaktywną poradę?"
 SETTING_ADVANCED_SHADERS:0 "Zaawansowane efekty shaderów"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T Zaawansowane efekty cieni#!\nTa opcja włącza zaawansowane efekty cieniowania. Wyłączenie jej może zwiększyć wydajność kosztem pogorszenia wyglądu niektórych efektów (np. terenu i wody)"
 BASED_ON_ZOOM_LEVEL:0 "Dynamiczne"
 ALWAYS_HIDE:0 "Zawsze ukryte"
 ALWAYS_SHOW:0 "Zawsze pokazuj"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "Granice przybrzeżne"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nThis option will control when coastal realm borders should be shown.\nIf $BASED_ON_ZOOM_LEVEL$ then they will be hidden in the detail zoom level.\n\nPicking a $ALWAYS_SHOW$ or $ALWAYS_HIDE$ may increase performance at the cost of the coastal realm borders not hiding dynamically."
