l_english:
 SETTINGS_PAGE_GRAPHICS:0 "Grafika"
 SETTINGS_PAGE_GAME:0 "Gra"
 SETTINGS_PAGE_SYSTEM:0 "System"
 SETTINGS_PAGE_CONTROLS:0 "Sterowanie"
 SETTINGS_PAGE_EDITOR:0 "Edytor"
 SETTINGS_PAGE_INTERFACE:0 "Interfejs"
 SETTINGS_PAGE_AUDIO:0 "Dźwięk"
 SETTINGS_CATEGORY_SCREEN:0 "Ekran"
 SETTINGS_CATEGORY_QUALITY:0 "Jakość"
 OPTION_EASY:0 "Łatwy"
 OPTION_NORMAL:0 "Normalny"
 OPTION_HARD:0 "Trudny"
 OPTION_NEVER:0 "Nigdy"
 OPTION_MONTHLY:0 "Co miesiąc"
 OPTION_HALFYEAR:0 "Co pół roku"
 OPTION_YEARLY:0 "Co rok"
 OPTION_FIVE_YEAR:0 "Co pięć lat"
 OPTION_NO_AUTOSAVE:0 "Brak autozapisu"
 SETTINGS_CATEGORY_ACCOUNT:0 "Konto"
 SETTINGS_CATEGORY_SYSTEM:0 "System"
 SETTINGS_CATEGORY_CONTROLS:0 "Sterowanie"
 SETTINGS_CATEGORY_CAMERA:0 "Kamera"
 SETTINGS_CATEGORY_AUDIO:0 "Dźwięk"
 SETTINGS_CATEGORY_GUI:0 "GUI"
 RESTORE:0 "Przywróć"
 SAVE_AND_CLOSE:0 "OK"
 SETTINGS:0 "Ustawienia"
 REQUIRES_RESTART:0 "Wymaga restartu"
 REQUIRE_RESTART_DESCRIPTION:0 "Niektóre ustawienia zaczną działać dopiero po ponownym uruchomieniu gry."
